/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package group2_GUI;

import group2.*;
import static group2_JDBC.DBProject.popolaMantainer;
import static group2_JDBC.DBProject.popolaPlannedActivity;
import static group2_JDBC.DBProject.popolaUnplannedActivity;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;
import javax.swing.JOptionPane;
import java.util.regex.Pattern;
import static java.util.regex.Pattern.matches;
/**
 *
 * @author maria
 */
public class ManageMaintenance extends javax.swing.JFrame {

    private static List<String> activity_description = new ArrayList();
    /**
     * Creates new form ManageMantainers
     */
    public ManageMaintenance() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        ShowButton = new javax.swing.JButton();
        WeekText = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        ActivityTable = new javax.swing.JTable();
        Select1Button = new javax.swing.JButton();
        Select2Button = new javax.swing.JButton();
        Select3Button = new javax.swing.JButton();
        Select4Button = new javax.swing.JButton();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable1);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 472, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 305, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 102, 0));

        jPanel2.setBackground(new java.awt.Color(255, 102, 0));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Activity Selection");
        jLabel1.setToolTipText("");

        ShowButton.setBackground(new java.awt.Color(153, 153, 153));
        ShowButton.setText("Show");
        ShowButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ShowButtonActionPerformed(evt);
            }
        });

        WeekText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                WeekTextActionPerformed(evt);
            }
        });

        jLabel2.setText("Week n°");

        ActivityTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "ID", "AREA", "TYPE", "ESTIMATED TIME"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        ActivityTable.setToolTipText("");
        ActivityTable.setName(""); // NOI18N
        ActivityTable.setRowHeight(29);
        jScrollPane1.setViewportView(ActivityTable);
        ActivityTable.getAccessibleContext().setAccessibleName("");

        Select1Button.setBackground(new java.awt.Color(153, 153, 153));
        Select1Button.setText("Select1");
        Select1Button.setMaximumSize(new java.awt.Dimension(73, 33));
        Select1Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Select1ButtonActionPerformed(evt);
            }
        });

        Select2Button.setBackground(new java.awt.Color(153, 153, 153));
        Select2Button.setText("Select2");
        Select2Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Select2ButtonActionPerformed(evt);
            }
        });

        Select3Button.setBackground(new java.awt.Color(153, 153, 153));
        Select3Button.setText("Select3");
        Select3Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Select3ButtonActionPerformed(evt);
            }
        });

        Select4Button.setBackground(new java.awt.Color(153, 153, 153));
        Select4Button.setText("Select4");
        Select4Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Select4ButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 381, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Select3Button, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Select4Button, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Select2Button, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Select1Button, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(58, 58, 58)
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(WeekText, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(53, 53, 53)
                                .addComponent(ShowButton, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(22, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 23, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(WeekText, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ShowButton, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(50, 50, 50)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(Select1Button, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Select2Button)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Select3Button)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Select4Button))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void WeekTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_WeekTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_WeekTextActionPerformed

    private void Select1ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Select1ButtonActionPerformed
        String col = " ";
        MaintenanceActivityVerification mav = new MaintenanceActivityVerification();
        mav.setVisible(true);
        mav.WeekText2.setText(WeekText.getText());
        mav.WeekText2.setEditable(false);
        for (int i=0; i<3; i++){
             col += " " + (String) ActivityTable.getValueAt(0, i);     
        }
        col += " " + ActivityTable.getValueAt(0, 3);
        mav.ActivityText1.setText(col); //da finire
        mav.ActivityText1.setEditable(false);
        mav.DescriptionText.setText(activity_description.get(0));
        mav.DescriptionText.setEditable(false);
    }//GEN-LAST:event_Select1ButtonActionPerformed

    private void ShowButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ShowButtonActionPerformed
        String week = WeekText.getText();
        
        if(!matches("-?\\d+(\\.\\d+)?",week)){
            JOptionPane p = new JOptionPane();
            JOptionPane.showMessageDialog(p, "ERRORE, hai inserito una stringa, non un numero", "ERROR!", JOptionPane.ERROR_MESSAGE);
            WeekText.setText("");
        }
        else {
        int w = Integer.parseInt(week);
        int row = 0;
        if ((w < 0 || w > 52)&&matches("-?\\d+(\\.\\d+)?",week)) {
            JOptionPane p = new JOptionPane();
            JOptionPane.showMessageDialog(p, "ERRORE, non hai inserito il numero di settimana correttamente. Inserisci un numero tra 0 e 52", "ERROR!", JOptionPane.ERROR_MESSAGE);
            WeekText.setText("");
        }
        List<PlannedActivity> p = popolaPlannedActivity(w);
        List<UnplannedActivity> u = popolaUnplannedActivity(w);

        ActivityTable.setModel(new javax.swing.table.DefaultTableModel(
                new Object[][]{
                    {null, null, null, null},
                    {null, null, null, null},
                    {null, null, null, null},
                    {null, null, null, null}
                },
                new String[]{
                    "ID", "AREA", "TYPE", "ESTIMATED TIME"
                }
        ));
        for (int i = 0; i < p.size(); i++) { //TODO RIEMPIRE I CAMPI DELLA TABLE
            PlannedActivity pa = p.get(i); //pa.getID(), pa.getArea(), pa.getTipology(), pa.getEstimatedTime()

            //ActivityTable da rivedere
            ActivityTable.setValueAt(pa.getID(), row, 0);
            ActivityTable.setValueAt(pa.getArea(), row, 1);
            ActivityTable.setValueAt(pa.getTipology(), row, 2);
            ActivityTable.setValueAt(pa.getEstimatedTime(), row, 3);
            activity_description.add(pa.getDescription());
            row ++ ;                                                    //Gestire il caso di più di 4 righe
        }
        for (int i = 0; i < u.size(); i++) { //TODO RIEMPIRE I CAMPI DELLA TABLE
            UnplannedActivity up = u.get(i); //pa.getID(), pa.getArea(), pa.getTipology(), pa.getEstimatedTime()

            //ActivityTable da rivedere
            ActivityTable.setValueAt(up.getID(), row, 0);
            ActivityTable.setValueAt(up.getArea(), row, 1);
            ActivityTable.setValueAt(up.getTipology(), row, 2);
            ActivityTable.setValueAt(up.getEstimatedTime(), row, 3);
            activity_description.add(up.getDescription());
            row ++;                              //Gestire il caso di più di 4 righe
        }
        }
    }//GEN-LAST:event_ShowButtonActionPerformed

    private void Select2ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Select2ButtonActionPerformed
        String col = " ";
        MaintenanceActivityVerification mav = new MaintenanceActivityVerification();
        mav.setVisible(true);
        mav.WeekText2.setText(WeekText.getText());
        mav.WeekText2.setEditable(false);
        for (int i=0; i<3; i++){
            col += " " + (String) ActivityTable.getValueAt(1, i);     
        }
        col += " " + ActivityTable.getValueAt(1, 3);
        mav.ActivityText1.setText(col); //da finire
        mav.ActivityText1.setEditable(false);
        mav.DescriptionText.setText(activity_description.get(1));
        mav.DescriptionText.setEditable(false);
    }//GEN-LAST:event_Select2ButtonActionPerformed

    private void Select3ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Select3ButtonActionPerformed
        String col = " ";        
        MaintenanceActivityVerification mav = new MaintenanceActivityVerification();
        mav.setVisible(true);
        mav.WeekText2.setText(WeekText.getText());
        mav.WeekText2.setEditable(false);
        for (int i=0; i<3; i++){
            col += " " + (String) ActivityTable.getValueAt(2, i);    
        }
        col += " " + ActivityTable.getValueAt(2, 3);
        mav.ActivityText1.setText(col); //da finire
        mav.ActivityText1.setEditable(false);
        mav.DescriptionText.setText(activity_description.get(2));
        mav.DescriptionText.setEditable(false);
    }//GEN-LAST:event_Select3ButtonActionPerformed

    private void Select4ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Select4ButtonActionPerformed
        String col = " ";
        MaintenanceActivityVerification mav = new MaintenanceActivityVerification();
        mav.setVisible(true);
        mav.WeekText2.setText(WeekText.getText());
        mav.WeekText2.setEditable(false);
        for (int i=0; i<3; i++){
            col += " " + (String) ActivityTable.getValueAt(3, i);     
        }
        col += " " + ActivityTable.getValueAt(3, 3);
        mav.ActivityText1.setText(col); //da finire 
        mav.ActivityText1.setEditable(false);
        mav.DescriptionText.setText(activity_description.get(3));
        mav.DescriptionText.setEditable(false);
    }//GEN-LAST:event_Select4ButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {  //la gui deve sempre essere connessa al DB
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ManageMaintenance.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ManageMaintenance.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ManageMaintenance.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ManageMaintenance.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ManageMaintenance().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable ActivityTable;
    private javax.swing.JButton Select1Button;
    private javax.swing.JButton Select2Button;
    private javax.swing.JButton Select3Button;
    private javax.swing.JButton Select4Button;
    private javax.swing.JButton ShowButton;
    private javax.swing.JTextField WeekText;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
